name: Run Pytest

on: [push, pull_request]  # Runs on every push or pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on Ubuntu
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Use the correct version of Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  

      - name: Run tests
        run: pytest
